group:
  - files:
      - source: DividendDetail/
        dest:   DividendDetail/
        deleteOrphaned: true
      - source: EquityDistribution/
        dest:   EquityDistribution/
        deleteOrphaned: true
      - source: ShowSaleMonChart/
        dest:   ShowSaleMonChart/
        deleteOrphaned: true
      - source: StockBzPerformance/
        dest:   StockBzPerformance/
        deleteOrphaned: true
      - source: StockBzPerformance1/
        dest:   StockBzPerformance1/
        deleteOrphaned: true
      - source: ShowK_ChartFlow/
        dest: ShowK_ChartFlow/
        deleteOrphaned: true
      - source: StockDetail/
        dest: StockDetail/
        deleteOrphaned: true
    repos: |
        wenchiehlee-investment/Python-Actions.GoodInfo
        wenchiehlee-investment/Python-Actions.GoodInfo.Analyzer
